# Generated by Django 3.2.6 on 2024-06-26 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godigital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledate',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 21, 50, 7, 570781)),
        ),
    ]
