# Generated by Django 4.0.6 on 2024-06-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_monthyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='day_off_1',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='day_off_2',
        ),
        migrations.AddField(
            model_name='schedule',
            name='dayoff',
            field=models.IntegerField(choices=[(1, 'Mon-Tue'), (2, 'Tue-Wed'), (3, 'Wed-Thur'), (4, 'Thu-Fri'), (5, 'Fri-Sat'), (6, 'Sat-Sun'), (7, 'Sun-Mon')], default=0),
        ),
    ]
