# Generated by Django 3.2.6 on 2024-06-26 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godigital', '0002_alter_scheduledate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledate',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 21, 55, 16, 668361)),
        ),
    ]
