# Generated by Django 4.0.6 on 2024-07-04 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godigital', '0002_alter_scheduledate_date_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aircraft_type', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('flt_no', models.CharField(max_length=50)),
                ('svc_chk_action_taken', models.CharField(max_length=255)),
                ('arr_time', models.TimeField()),
                ('dep_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='scheduledate',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 4, 14, 58, 4, 766669)),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='emp_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
