# Generated by Django 5.0.6 on 2024-07-04 15:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godigital", "0003_servicelog_alter_scheduledate_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorAirline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="scheduledate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 4, 15, 56, 59, 436337)
            ),
        ),
        migrations.AddField(
            model_name="aircrafts",
            name="operator_airline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircrafts",
                to="godigital.operatorairline",
            ),
        ),
    ]
