# Generated by Django 5.0.6 on 2024-07-05 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godigital", "0004_operatorairline_alter_scheduledate_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelog",
            name="operator_airline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="godigital.operatorairline",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 5, 20, 9, 3, 261060)
            ),
        ),
    ]
