# Generated by Django 4.0.6 on 2024-06-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_schedule_dayoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dayoff',
            field=models.CharField(choices=[('Mon-Tue', 'Mon-Tue'), ('Tue-Wed', 'Tue-Wed'), ('Wed-Thur', 'Wed-Thur'), ('Thu-Fri', 'Thu-Fri'), ('Fri-Sat', 'Fri-Sat'), ('Sat-Sun', 'Sat-Sun'), ('Sun-Mon', 'Sun-Mon')], max_length=8),
        ),
    ]
