# Generated by Django 5.0.6 on 2024-07-05 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godigital", "0005_servicelog_operator_airline_alter_scheduledate_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 5, 20, 10, 18, 352367)
            ),
        ),
    ]
