# Generated by Django 4.0.6 on 2024-06-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_schedule_dayoff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('technician', 'month', 'year')},
        ),
    ]
