# Generated by Django 5.0.6 on 2024-07-06 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godigital", "0008_alter_scheduledate_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 6, 8, 38, 10, 250666)
            ),
        ),
    ]
