# Generated by Django 5.0.6 on 2024-07-14 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godigital", "0010_alter_scheduledate_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 14, 13, 9, 21, 629815)
            ),
        ),
    ]
